package com.swd392.preOrderBlindBox.common.enums;

public enum PreorderStatus {
  DEPOSIT_PENDING,
  DEPOSIT_FAILED,
  DEPOSIT_SUCCESSFUL,
  FULL_PAYMENT_PENDING,
  FULL_PAYMENT_FAILED,
  FULL_PAYMENT_SUCCESSFUL,
  PENDING_FOR_DELIVERY,
  IN_DELIVERY,
  DELIVERY_SUCCESS,
  DELIVERY_FAILED,
  PREORDER_COMPLETED,
  PREORDER_FAILED,
  CANCELED
}
