package com.swd392.preOrderBlindBox.enums;

public enum OrderStatus {
  IN_CART,
  PAYMENT_PENDING,
  PAYMENT_FAILED,
  PAYMENT_SUCCESSFUL,
  PREORDER_PENDING,
  ORDER_PENDING,
  IN_DELIVERY,
  DELIVERY_SUCCESS,
  DELIVERY_FAILED,
  ORDER_COMPLETED,
  ORDER_FAILED,
  CANCELED;
}
